USE COMPASS
DECLARE @column VARCHAR(30) = 'uid'

SELECT  COLUMN_NAME,
        DATA_TYPE,
        CHARACTER_MAXIMUM_LENGTH, 
        TABLE_NAME 
FROM    INFORMATION_SCHEMA.COLUMNS 
WHERE   COLUMN_NAME LIKE '%' + @column + '%'
ORDER BY TABLE_NAME