/****** Script for SelectTopNRows command from SSMS  ******/
DECLARE @action VARCHAR(100) = '',
        @user VARCHAR(100) = '',
        @date DATETIME = ''

IF (@date <> '')
BEGIN
  SELECT  [action],
          [uid],
          CASE WHEN SUM([6C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,SUM([6C])) END AS [6:00 Count],
          CASE WHEN SUM([6C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MAX([6S])) / 1000)) END AS [6:00 Max],
          CASE WHEN SUM([6C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MIN([6S])) / 1000)) END AS [6:00 Min],
          CASE WHEN SUM([6C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,SUM([6S]) / SUM([6C] )) / 1000)) END AS [6:00 Avg],
          CASE WHEN SUM([7C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,SUM([7C])) END AS [7:00 Count],
          CASE WHEN SUM([7C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MAX([7S])) / 1000)) END AS [7:00 Max],
          CASE WHEN SUM([7C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MIN([7S])) / 1000)) END AS [7:00 Min],
          CASE WHEN SUM([7C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,SUM([7S]) / SUM([7C] )) / 1000)) END AS [7:00 Avg],
          CASE WHEN SUM([8C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,SUM([8C])) END AS [8:00 Count],
          CASE WHEN SUM([8C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MAX([8S])) / 1000)) END AS [8:00 Max],
          CASE WHEN SUM([8C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MIN([8S])) / 1000)) END AS [8:00 Min],
          CASE WHEN SUM([8C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,SUM([8S]) / SUM([8C] )) / 1000)) END AS [8:00 Avg],
          CASE WHEN SUM([9C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,SUM([9C])) END AS [9:00 Count],
          CASE WHEN SUM([9C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MAX([9S])) / 1000)) END AS [9:00 Max],
          CASE WHEN SUM([9C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MIN([9S])) / 1000)) END AS [9:00 Min],
          CASE WHEN SUM([9C] ) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,SUM([9S]) / SUM([9C] )) / 1000)) END AS [9:00 Avg],
          CASE WHEN SUM([10C]) = 0 THEN '' ELSE CONVERT(VARCHAR,SUM([10C])) END AS [10:00 Count],
          CASE WHEN SUM([10C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MAX([10S])) / 1000)) END AS [10:00 Max],
          CASE WHEN SUM([10C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MIN([10S])) / 1000)) END AS [10:00 Min],
          CASE WHEN SUM([10C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,SUM([10S]) / SUM([10C] )) / 1000)) END AS [10:00 Avg],
          CASE WHEN SUM([11C]) = 0 THEN '' ELSE CONVERT(VARCHAR,SUM([11C])) END AS [11:00 Count],
          CASE WHEN SUM([11C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MAX([11S])) / 1000)) END AS [11:00 Max],
          CASE WHEN SUM([11C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MIN([11S])) / 1000)) END AS [11:00 Min],
          CASE WHEN SUM([11C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,SUM([11S]) / SUM([11C] )) / 1000)) END AS [11:00 Avg],
          CASE WHEN SUM([12C]) = 0 THEN '' ELSE CONVERT(VARCHAR,SUM([12C])) END AS [12:00 Count],
          CASE WHEN SUM([12C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MAX([12S])) / 1000)) END AS [12:00 Max],
          CASE WHEN SUM([12C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MIN([12S])) / 1000)) END AS [12:00 Min],
          CASE WHEN SUM([12C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,SUM([12S]) / SUM([12C] )) / 1000)) END AS [12:00 Avg],
          CASE WHEN SUM([13C]) = 0 THEN '' ELSE CONVERT(VARCHAR,SUM([13C])) END AS [13:00 Count],
          CASE WHEN SUM([13C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MAX([13S])) / 1000)) END AS [13:00 Max],
          CASE WHEN SUM([13C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MIN([13S])) / 1000)) END AS [13:00 Min],
          CASE WHEN SUM([13C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,SUM([13S]) / SUM([13C] )) / 1000)) END AS [13:00 Avg],
          CASE WHEN SUM([14C]) = 0 THEN '' ELSE CONVERT(VARCHAR,SUM([14C])) END AS [14:00 Count],
          CASE WHEN SUM([14C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MAX([14S])) / 1000)) END AS [14:00 Max],
          CASE WHEN SUM([14C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MIN([14S])) / 1000)) END AS [14:00 Min],
          CASE WHEN SUM([14C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,SUM([14S]) / SUM([14C] )) / 1000)) END AS [14:00 Avg],
          CASE WHEN SUM([15C]) = 0 THEN '' ELSE CONVERT(VARCHAR,SUM([15C])) END AS [15:00 Count],
          CASE WHEN SUM([15C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MAX([15S])) / 1000)) END AS [15:00 Max],
          CASE WHEN SUM([15C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MIN([15S])) / 1000)) END AS [15:00 Min],
          CASE WHEN SUM([15C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,SUM([15S]) / SUM([15C] )) / 1000)) END AS [15:00 Avg],
          CASE WHEN SUM([16C]) = 0 THEN '' ELSE CONVERT(VARCHAR,SUM([16C])) END AS [16:00 Count],
          CASE WHEN SUM([16C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MAX([16S])) / 1000)) END AS [16:00 Max],
          CASE WHEN SUM([16C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MIN([16S])) / 1000)) END AS [16:00 Min],
          CASE WHEN SUM([16C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,SUM([16S]) / SUM([16C] )) / 1000)) END AS [16:00 Avg],
          CASE WHEN SUM([17C]) = 0 THEN '' ELSE CONVERT(VARCHAR,SUM([17C])) END AS [17:00 Count],
          CASE WHEN SUM([17C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MAX([17S])) / 1000)) END AS [17:00 Max],
          CASE WHEN SUM([17C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MIN([17S])) / 1000)) END AS [17:00 Min],
          CASE WHEN SUM([17C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,SUM([17S]) / SUM([17C] )) / 1000)) END AS [17:00 Avg],
          CASE WHEN SUM([18C]) = 0 THEN '' ELSE CONVERT(VARCHAR,SUM([18C])) END AS [18:00 Count],
          CASE WHEN SUM([18C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MAX([18S])) / 1000)) END AS [18:00 Max],
          CASE WHEN SUM([18C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,MIN([18S])) / 1000)) END AS [18:00 Min],
          CASE WHEN SUM([18C]) = 0 THEN '' ELSE CONVERT(VARCHAR,CONVERT(DECIMAL(18,2),CONVERT(DECIMAL,SUM([18S]) / SUM([18C] )) / 1000)) END AS [18:00 Avg]
  FROM    (
          SELECT  [action],
                  [uid],
                  CONVERT(VARCHAR,DATEPART(HOUR,[createDate])) + 'C' AS [ch],
                  CONVERT(VARCHAR,DATEPART(HOUR,[createDate])) + 'S' AS [sh],
                  [duration] AS [count],
                  [duration] AS [seconds]
          FROM    [dbo].[syslog]
          WHERE   [action] LIKE CASE WHEN @action = '' THEN '%%' ELSE '%' + @action + '%' END
          AND     [uid] = CASE WHEN @user = '' THEN [uid] ELSE @user END
          AND     CONVERT(DATE,[createDate],101) = @date
          GROUP BY [action], [uid], DATEPART(HOUR,[createDate]), [duration]
          ) src
          PIVOT
          (
          SUM([seconds])
          FOR [sh] IN ([6S],[7S],[8S],[9S],[10S],[11S],[12S],[13S],[14S],[15S],[16S],[17S],[18S])
          ) p1
          PIVOT
          (
          COUNT([count])
          FOR [ch] IN ([6C],[7C],[8C],[9C],[10C],[11C],[12C],[13C],[14C],[15C],[16C],[17C],[18C])
          ) p2
  WHERE   [action] <> 'ping'
  GROUP BY [action],[uid]
END
ELSE
  BEGIN
  IF (@action <> '')
  BEGIN
    SELECT  *
    FROM    [dbo].[syslog]
    WHERE   [action] = @action
    AND     [uid] = CASE WHEN @user = '' THEN [uid] ELSE @user END
    ORDER BY [duration] DESC
  END
  ELSE
  BEGIN
    SELECT  [action],
            COUNT(*) AS [timesRan],
            CONVERT(DECIMAL(18,2), MAX(CONVERT(DECIMAL, [duration])) / 1000) AS [maximum],
            CONVERT(DECIMAL(18,2), MIN(CONVERT(DECIMAL, [duration])) / 1000) AS [minimum],
            CONVERT(DECIMAL(18,2), SUM(CONVERT(DECIMAL, [duration])) / COUNT(CONVERT(DECIMAL, [duration])) / 1000) AS [seconds]
    FROM    [dbo].[syslog]
    WHERE   [uid] = CASE WHEN @user = '' THEN [uid] ELSE @user END
    GROUP BY [action]
    ORDER BY [seconds] DESC
  END
END